### ISSUE TITLE
[1.7.2][Modular Pots 1.7.2.10] Crash: Placing seeds in flowerpot with farmland.

### ISSUE THREAD

**Issue by DBerke** [jaquadro/ForgeMods#2]
As indicated in the title; I got the following crash several times in a row when trying to plant vanillia Seeds in a modular flower pot made of hardened clay. The crash happened with both farmland and plain dirt in the pot.

(Sorry if this isn't how you prefer bug reports, this was just the easiest way for me. Let me know and I can change in future.)

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/3/14 10:30 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at com.jaquadro.minecraft.modularpots.registry.PlantRegistry.isBlacklisted(PlantRegistry.java:40)
    at com.jaquadro.minecraft.modularpots.block.BlockLargePot.canSustainPlantActivated(BlockLargePot.java:559)
    at com.jaquadro.minecraft.modularpots.block.BlockLargePot.func_149727_a(BlockLargePot.java:352)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1397)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1901)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:914)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:833)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at com.jaquadro.minecraft.modularpots.registry.PlantRegistry.isBlacklisted(PlantRegistry.java:40)
    at com.jaquadro.minecraft.modularpots.block.BlockLargePot.canSustainPlantActivated(BlockLargePot.java:559)
    at com.jaquadro.minecraft.modularpots.block.BlockLargePot.func_149727_a(BlockLargePot.java:352)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1397)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Philadelphus'/174, l='MpServer', x=117.37, y=74.56, z=316.56]]
    Chunk stats: MultiplayerChunkCache: 225, 225
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (236,64,-96), Chunk: (at 12,4,0 in 14,-6; contains blocks 224,0,-96 to 239,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 156799 game time, 162509 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 94 total; [EntitySquid['Squid'/275, l='MpServer', x=85.16, y=56.38, z=329.31], EntitySquid['Squid'/274, l='MpServer', x=90.91, y=56.31, z=331.75], EntityCow['Cow'/273, l='MpServer', x=81.03, y=71.00, z=282.16], EntitySquid['Squid'/283, l='MpServer', x=103.97, y=58.36, z=304.50], EntitySquid['Squid'/282, l='MpServer', x=109.32, y=59.00, z=300.50], EntityCow['Cow'/281, l='MpServer', x=111.44, y=72.00, z=265.31], EntityCow['Cow'/280, l='MpServer', x=102.94, y=70.00, z=244.03], EntityZombie['Zombie'/258, l='MpServer', x=50.50, y=65.00, z=313.50], EntityPig['Pig'/259, l='MpServer', x=52.03, y=64.00, z=333.81], EntityZombie['Zombie'/256, l='MpServer', x=57.89, y=40.00, z=313.31], EntityZombie['Zombie'/257, l='MpServer', x=49.50, y=44.00, z=313.50], EntitySpider['Spider'/262, l='MpServer', x=63.81, y=64.00, z=354.09], EntitySpider['Spider'/263, l='MpServer', x=60.38, y=64.00, z=354.34], EntityCow['Cow'/260, l='MpServer', x=48.97, y=64.00, z=351.94], EntityPig['Pig'/261, l='MpServer', x=57.09, y=64.00, z=340.72], EntityZombie['Zombie'/267, l='MpServer', x=69.53, y=66.04, z=280.31], EntityPig['Pig'/268, l='MpServer', x=65.16, y=64.00, z=346.50], EntitySkeleton['Skeleton'/309, l='MpServer', x=132.50, y=19.00, z=239.50], EntityCow['Cow'/175, l='MpServer', x=120.53, y=65.08, z=301.71], EntitySkeleton['Skeleton'/311, l='MpServer', x=134.47, y=16.00, z=243.44], EntityItem['item.tile.botania:flower11'/313, l='MpServer', x=133.81, y=70.13, z=260.13], EntityZombie['Zombie'/312, l='MpServer', x=136.56, y=16.00, z=244.70], EntityCow['Cow'/315, l='MpServer', x=138.97, y=63.00, z=376.88], EntityPig['Pig'/314, l='MpServer', x=143.91, y=64.00, z=357.06], EntityCreeper['Creeper'/316, l='MpServer', x=130.56, y=62.25, z=369.00], EntityTFNagaSegment['unknown'/425, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/424, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/427, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/426, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/428, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityBat['Bat'/295, l='MpServer', x=124.50, y=37.00, z=245.31], EntityBat['Bat'/296, l='MpServer', x=116.53, y=26.87, z=255.94], EntityTFNagaSegment['unknown'/417, l='MpServer', x=0.60, y=-26.00, z=0.60], EntitySpider['Spider'/297, l='MpServer', x=128.13, y=71.00, z=265.41], EntityTFNagaSegment['unknown'/419, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityCow['Cow'/298, l='MpServer', x=114.91, y=72.00, z=261.03], EntitySpider['Spider'/299, l='MpServer', x=124.09, y=62.07, z=375.50], EntityClientPlayerMP['Philadelphus'/174, l='MpServer', x=117.37, y=74.56, z=316.56], EntityTFNagaSegment['unknown'/418, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityCreeper['Creeper'/300, l='MpServer', x=119.16, y=63.00, z=391.10], EntityTFNagaSegment['unknown'/421, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/420, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/423, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityTFNagaSegment['unknown'/422, l='MpServer', x=0.60, y=-26.00, z=0.60], EntityZombie['Zombie'/343, l='MpServer', x=163.50, y=72.00, z=267.50], EntityCow['Cow'/351, l='MpServer', x=165.69, y=64.00, z=361.72], EntityCow['Cow'/350, l='MpServer', x=165.19, y=67.00, z=322.06], EntityCow['Cow'/349, l='MpServer', x=166.13, y=65.00, z=320.34], EntityCow['Cow'/348, l='MpServer', x=168.41, y=68.00, z=322.78], EntitySquid['Squid'/347, l='MpServer', x=164.59, y=59.16, z=312.50], EntitySquid['Squid'/346, l='MpServer', x=156.53, y=59.00, z=309.38], EntityZombie['Zombie'/345, l='MpServer', x=169.50, y=75.00, z=290.50], EntityZombie['Zombie'/344, l='MpServer', x=168.50, y=75.00, z=291.50], EntityCow['Cow'/326, l='MpServer', x=142.03, y=69.00, z=251.13], EntityCow['Cow'/327, l='MpServer', x=149.44, y=72.00, z=264.31], EntityCreeper['Creeper'/324, l='MpServer', x=158.97, y=29.00, z=268.59], EntityCreeper['Creeper'/223, l='MpServer', x=46.41, y=65.00, z=296.00], EntityCow['Cow'/325, l='MpServer', x=148.66, y=71.00, z=256.31], EntityZombie['Zombie'/322, l='MpServer', x=159.50, y=40.00, z=240.50], EntityZombie['Zombie'/217, l='MpServer', x=41.97, y=29.00, z=255.53], EntityCow['Cow'/323, l='MpServer', x=151.59, y=71.00, z=257.34], EntityPig['Pig'/218, l='MpServer', x=44.94, y=68.00, z=265.13], EntityZombie['Zombie'/321, l='MpServer', x=158.50, y=40.00, z=238.50], EntityPig['Pig'/219, l='MpServer', x=45.66, y=69.00, z=258.91], EntityCow['Cow'/332, l='MpServer', x=147.78, y=64.00, z=338.81], EntityCow['Cow'/333, l='MpServer', x=156.81, y=63.00, z=378.75], EntitySquid['Squid'/330, l='MpServer', x=152.19, y=59.00, z=309.50], EntitySquid['Squid'/331, l='MpServer', x=157.78, y=58.78, z=306.22], EntitySkeleton['Skeleton'/328, l='MpServer', x=148.16, y=71.00, z=261.25], EntitySquid['Squid'/329, l='MpServer', x=149.56, y=61.25, z=306.16], EntitySkeleton['Skeleton'/239, l='MpServer', x=43.50, y=64.00, z=370.50], EntitySkeleton['Skeleton'/238, l='MpServer', x=50.09, y=64.00, z=381.44], EntitySpider['Spider'/375, l='MpServer', x=192.28, y=67.00, z=293.16], EntityBat['Bat'/236, l='MpServer', x=44.58, y=16.95, z=351.53], EntityPig['Pig'/369, l='MpServer', x=172.09, y=64.00, z=365.19], EntitySpider['Spider'/368, l='MpServer', x=179.13, y=64.00, z=319.13], EntityPig['Pig'/230, l='MpServer', x=41.75, y=63.00, z=351.59], EntityCreeper['Creeper'/229, l='MpServer', x=42.50, y=22.00, z=349.50], EntityBat['Bat'/227, l='MpServer', x=44.56, y=11.02, z=326.09], EntityCow['Cow'/226, l='MpServer', x=44.13, y=66.00, z=311.16], EntityCreeper['Creeper'/224, l='MpServer', x=46.00, y=65.00, z=297.34], EntityZombie['Zombie'/254, l='MpServer', x=55.50, y=27.00, z=306.50], EntityZombie['Zombie'/255, l='MpServer', x=55.50, y=27.00, z=305.50], EntitySkeleton['Skeleton'/252, l='MpServer', x=54.50, y=66.00, z=273.50], EntityZombie['Zombie'/253, l='MpServer', x=51.97, y=29.00, z=304.50], EntityCreeper['Creeper'/250, l='MpServer', x=54.50, y=66.00, z=283.50], EntityCreeper['Creeper'/251, l='MpServer', x=55.50, y=66.00, z=279.50], EntityCreeper['Creeper'/249, l='MpServer', x=59.50, y=70.00, z=246.50], EntityZombie['Zombie'/364, l='MpServer', x=183.88, y=12.00, z=266.41], EntityCreeper['Creeper'/365, l='MpServer', x=189.50, y=67.00, z=296.50], EntityCreeper['Creeper'/366, l='MpServer', x=184.66, y=67.00, z=296.47], EntityBat['Bat'/367, l='MpServer', x=192.07, y=17.37, z=311.51], EntitySpider['Spider'/362, l='MpServer', x=177.97, y=40.00, z=247.94], EntityZombie['Zombie'/363, l='MpServer', x=173.53, y=68.00, z=252.05]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:368)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2380)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:862)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 316286536 bytes (301 MB) / 606601216 bytes (578 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 17299 (968744 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.01-pre FML v7.2.156.1060 Minecraft Forge 10.12.1.1060 25 mods loaded, 25 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.156.1060} [Forge Mod Loader] (forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.1.1060} [Minecraft Forge] (forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.0} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.1} [Not Enough Items] (NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.6.3} [BiblioCraft] (BiblioCraft[1.6.3][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{beta-28} [Botania] (Botania beta-28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.1.4} [Carpenter's Blocks] (Carpenter's Blocks v3.1.4 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.7.2-2.0.1.5} [Enchanting Plus] (EnchantingPlus-1.7.2-2.0.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0-prerelease-1} [Extra Utilities] (extrautilities-1.1.0-prerelease-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks] (InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.2_1.7.2} [Waila] (Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.3} [Jabba] (Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.1.1} [MapWriter] (MapWriter-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modularpots{1.7.2.10} [Modular Flower Pots] (ModularPots-1.7.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morpheus{1.7.2-1.3} [Morpheus] (morpheus-1.7.2-1.3.41.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    plantmegapack{3.00.08} [Plant Mega Pack] (Plant Mega Pack-1.7.2-3.00.08.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Roguelike{1.3.0} [Roguelike Dungeons] (roguelike-1.7.2-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplefluidtanks{1.7.2-1.1.0.8} [Simple Fluid Tanks] (simplefluidtanks-1.7.2-1.1.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    smoothbedrock{2.0.11.77} [SmoothBedrock] (SmoothBedrock-1.7.2-2.0.11.77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    supercraftingframe{1.7.2.3} [Super Crafting Frame] (supercraftingframe-1.7.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.0.10} [Baubles] (Baubles-1.7.2-1.0.0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.1.11} [Thaumcraft] (Thaumcraft-1.7.2-4.1.1.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest] (twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    taverns{2.2.1-0} [Village Taverns] (VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ender-Quarry Relfection Code:: No problems here
    Launched Version: 1.7.2-Forge10.12.1.1060
    LWJGL: 2.9.0
    OpenGL: GeForce GT 230M/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 3516 (196896 bytes; 0 MB) allocated, 36 (2016 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by jaquadro** [comment]
I believe this was fixed on May 22 in 1.7.2.12.  If not, please re-open.  Thanks.
